export const ROUTES = {
  root: "/",
  app: "/app",
  login: "/login",
  auth: "/auth",
  dashboard: "/app/dashboard",
  clients: "/app/clients",
  clientDetail: (clientId: string) => `/app/clients/${clientId}`,
  vehicles: "/app/vehicles",
  vehicleDetail: (vehicleId: string) => `/app/vehicles/${vehicleId}`,
  employees: "/app/employees",
  profile: "/app/profile",
  workOrders: "/app/work-orders",
  workOrderNew: "/app/work-orders/new",
  workOrderDetail: (workOrderId: string) => `/app/work-orders/${workOrderId}`,
  settings: "/app/settings",
  orders: "/app/orders",
  newOrder: "/app/new-order",
  today: "/app/today",
  cashDesk: "/app/cash-desk"
} as const;
