from __future__ import annotations

from typing import Any
from uuid import UUID

from sqlalchemy.orm import Session

from app.models.audit_log import AuditLog
from app.repositories.base import BaseRepositoryTenantScoped


class AuditLogRepository(BaseRepositoryTenantScoped[AuditLog]):
    """Data-access layer for tenant-scoped audit logs."""

    def __init__(self, db: Session, tenant_id: UUID | None = None):
        super().__init__(db=db, model=AuditLog, tenant_id=tenant_id)

    def create_log(
        self,
        *,
        user_id: UUID,
        action: str,
        entity: str,
        entity_id: UUID | None,
        metadata: dict[str, Any],
    ) -> AuditLog:
        """Create a single audit log record in tenant scope."""
        return self.create(
            user_id=user_id,
            action=action,
            entity=entity,
            entity_id=entity_id,
            metadata_json=metadata or {},
        )

    def list_logs(self, *, limit: int, offset: int) -> list[AuditLog]:
        """Return tenant logs ordered by newest first."""
        stmt = self.scoped_select().order_by(AuditLog.created_at.desc()).limit(limit).offset(offset)
        return list(self.db.execute(stmt).scalars().all())

    def list_entity_logs(self, *, entity: str, entity_id: UUID, limit: int, offset: int) -> list[AuditLog]:
        """Return logs for a concrete entity instance."""
        stmt = (
            self.scoped_select(AuditLog.entity == entity, AuditLog.entity_id == entity_id)
            .order_by(AuditLog.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        return list(self.db.execute(stmt).scalars().all())

    def list_user_logs(self, *, user_id: UUID, limit: int, offset: int) -> list[AuditLog]:
        """Return logs generated by a specific user."""
        stmt = (
            self.scoped_select(AuditLog.user_id == user_id)
            .order_by(AuditLog.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        return list(self.db.execute(stmt).scalars().all())
